#Game settings
IMAGE_DIR = "Images"
TITLE = "SAVE THE MOON!"
FPS = 60
SCORES_FILE = "best_scores.txt"

#Ball properties
BALL_ACC = 0.5
BALL_FRICTION = -0.12
BALL_GRAVITY = 0.8

BALL_JUMP = -20
BALL_JUMP_CUT = -5

#Shield
SHIELD_COOLDOWN = 5000
SHIELD_DURATION = 2000

#Enemies
ENEMY_SPAWN_DELAY = 2000
ENEMY_SIZE = 32

BULLET_SPAWN_TIME = 4000
LANDER_SPAWN_TIME = 8000

MIN_ENEMIES = 2
MAX_ENEMIES = 5

MIN_LANDERS = 1
MAX_LANDERS = 2

MIN_SPEED_X = 7
MAX_SPEED_X = 9

#Platform speed
PLATFORM_SPEED = 1

CLOUD_WIDTH_MIN = 50
CLOUD_WIDTH_MAX = 175